### ISSUE TITLE
celll id issue 

### ISSUE THREAD

**Issue by Mujjafar-Momin** [Zfinix/carrier_info#39]
i was using to get only carrier name but I am getting issue on this line 
      cellId: CellId.fromMap(map['cellId']),

E/flutter ( 8993): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
E/flutter ( 8993): #0      new TelephonyInfo.fromMap (package:carrier_info/src/models/android_carrier_data.dart:382:33)
E/flutter ( 8993): #1      new AndroidCarrierData.fromMap.<anonymous closure> (package:carrier_info/src/models/android_carrier_data.dart:64:58)
E/flutter ( 8993): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
E/flutter ( 8993): #3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
E/flutter ( 8993): #4      new List.from (dart:core-patch/array_patch.dart:37:17)
E/flutter ( 8993): #5      new AndroidCarrierData.fromMap (package:carrier_info/src/models/android_carrier_data.dart:63:22)
E/flutter ( 8993): #6      CarrierInfo.getAndroidInfo (package:carrier_info/src/carrier_info.dart:12:31)
E/flutter ( 8993): <asynchronous suspension>
E/flutter ( 8993): #7      SimName.init (package:ffclite/utils/app_device_info.dart:52:26)
E/flutter ( 8993): <asynchronous suspension>
E/flutter ( 8993): #8      main (package:ffclite/main.dart:23:3)
E/flutter ( 8993): <asynchronous suspension>
please check

**Comment by LarssK-TS** [comment]
did you manage to resolve this?

**Comment by saiful00000** [comment]
What is you android version?
